# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
